// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_Pilot_FreeJob.Models;

namespace ProjectPilotFreeJob.Migrations
{
    [DbContext(typeof(FreeJobDbContext))]
    [Migration("20191201212301_novasClasses")]
    partial class novasClasses
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Project_Pilot_FreeJob.Models.Cadastro", b =>
                {
                    b.Property<int>("CategoriaId");

                    b.Property<int>("ServicoId");

                    b.Property<int>("UsuarioId");

                    b.HasKey("CategoriaId", "ServicoId", "UsuarioId");

                    b.HasIndex("ServicoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Cadastro");
                });

            modelBuilder.Entity("Project_Pilot_FreeJob.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<int?>("ServicoId");

                    b.HasKey("CategoriaId");

                    b.HasIndex("ServicoId");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("Project_Pilot_FreeJob.Models.Servico", b =>
                {
                    b.Property<int>("ServicoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.HasKey("ServicoId");

                    b.ToTable("Servico");
                });

            modelBuilder.Entity("Project_Pilot_FreeJob.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro");

                    b.Property<string>("CEP");

                    b.Property<string>("CNH");

                    b.Property<string>("CPF");

                    b.Property<int?>("CategoriaId");

                    b.Property<string>("Cidade");

                    b.Property<DateTime>("DataDeNascimento");

                    b.Property<string>("Email");

                    b.Property<string>("Endereco");

                    b.Property<string>("Estado");

                    b.Property<int>("Idade");

                    b.Property<string>("Login");

                    b.Property<string>("Nome");

                    b.Property<string>("RG");

                    b.Property<string>("Senha");

                    b.Property<int?>("ServicoId");

                    b.Property<string>("Telefone");

                    b.HasKey("UsuarioId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ServicoId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Project_Pilot_FreeJob.Models.Cadastro", b =>
                {
                    b.HasOne("Project_Pilot_FreeJob.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Project_Pilot_FreeJob.Models.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Project_Pilot_FreeJob.Models.Usuario", "Usuario")
                        .WithMany("Cadastro")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Project_Pilot_FreeJob.Models.Categoria", b =>
                {
                    b.HasOne("Project_Pilot_FreeJob.Models.Servico")
                        .WithMany("Categoria")
                        .HasForeignKey("ServicoId");
                });

            modelBuilder.Entity("Project_Pilot_FreeJob.Models.Usuario", b =>
                {
                    b.HasOne("Project_Pilot_FreeJob.Models.Categoria")
                        .WithMany("Usuario")
                        .HasForeignKey("CategoriaId");

                    b.HasOne("Project_Pilot_FreeJob.Models.Servico")
                        .WithMany("Usuario")
                        .HasForeignKey("ServicoId");
                });
#pragma warning restore 612, 618
        }
    }
}
